target-version = "py310"

line-length = 100
indent-width = 4
[lint]
select = [
    "B",   # bugbear
    "D",   # pydocstyle
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "PIE", # flake8-pie
    "PTH", # flake8-pathlib
    "PYI", # flake8-pyi
    "UP",  # pyupgrade
    "RUF", # ruff
    "W",   # pycodestyle
    "PLR", # pylint
    "PL", # pylint
]

ignore = [
    "B905",   # `zip()` without an explicit `strict=` parameter
    "B028",
    "D100",   # Missing docstring in public module
    "D101",   # Missing docstring in public class
    "D102",   # Missing docstring in public method
    "D103",   # Missing docstring in public function
    "D104",   # Missing docstring in public package
    "D105",   # Missing docstring in magic method
    "D106",   # Missing docstring in public nested class
    "D107",   # Missing docstring in `__init__`
    "D205",   # 1 blank line required between summary line and description
    "D400",   # First line should end with a period
    "D401",   # First line of docstring should be in imperative mood
    "RUF012", # mutable default values in class attributes
    "D415"    #
]

[format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false
docstring-code-format = true


[lint.flake8-bugbear]
# Allow default arguments like, e.g., `data: List[str] = fastapi.Query(None)`.
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query", "fastapi.File"]